
[
    {
        "orderState":"Create",
        "orderId":188,
        "overlay":false,
        "debugMode":false,
        "stateLevel":0,
        "operator":"陆琥MA",
        "doWhat":"提交订单",
        "remark":null,
        "id":118,
        "date":1353249100000
    },{
        "orderState":"Pay",
        "orderId":188,
        "overlay":false,
        "debugMode":false,
        "stateLevel":0,
        "operator":"陆琥MA",
        "doWhat":"付款完成",
        "remark":null,
        "id":123,
        "date":1353249777000
    },{
        "orderState":"Verify",
        "orderId":188,
        "overlay":false,
        "debugMode":false,
        "stateLevel":0,
        "operator":"罗凤江",
        "doWhat":"已验货",
        "remark":null,
        "id":170,
        "date":1353379376000
    },{
        "orderState":"Send",
        "orderId":188,
        "overlay":false,
        "debugMode":false,
        "stateLevel":0,
        "operator":"罗凤江",
        "doWhat":"已发货",
        "remark":null,
        "id":177,
        "date":1353383215000
    },{
        "orderState":"Success",
        "orderId":188,
        "overlay":false,
        "debugMode":false,
        "stateLevel":0,
        "operator":"陆琥MA",
        "doWhat":"交易完成",
        "remark":null,
        "id":201,
        "date":1353842892000
    }
]
